### PR TITLE
chore: add type safety

### PR DESCRIPTION
**Pull request by shioju**
This PR adds more type safety.

- [x] I've requested reviews from 1 reviewer
- [x] I've tested existing features (website scan, sitemap, custom flow) in both node index and cli

### CODE REVIEW

**Comment by younglim** [comment]
@shioju Just fyi, we will be removing the original Custom Flow from the codebase this week (not to be confused with Custom Flow 2.0).  So don't bother to fix playwrightAxeGenerator.ts and runCustomFlowFromGUI.ts

Cc @joshualai9922

**Comment by shioju** [comment]
> @shioju Just fyi, we will be removing the original Custom Flow from the codebase this week (not to be confused with Custom Flow 2.0). So don't bother to fix playwrightAxeGenerator.ts and runCustomFlowFromGUI.ts
> 
> Cc @joshualai9922

Noted. Thanks for the info!

**Comment by younglim** [comment]
Encountering the following error:

Command:
```
export PURPLE_A11Y_VERBOSE=1
npm run cli -- -c 2 -u "https://www.tech.gov.sg/" -k "..." -i all -p 5 -t 10 -a none -f yes -h yes
```
Error:
```
{"timestamp":"2024-06-07 09:11:32","level":"error","message":"uncaughtException: Cannot read properties of undefined (reading 'split')\nTypeError: Cannot read properties of undefined (reading 'split')\n    at combineRun (file:///Users/young/purple-a11y/dist/combine.js:69:41)\n    at async scanInit (file:///Users/young/purple-a11y/dist/cli.js:264:5)"}
```

**Review by younglim — APPROVED** [review]

**Comment by younglim** [comment]
@shioju fyi this logic to prioritise Chrome on win32 and darwin was missing in the migration.  Users should not have to install chromium and the portable package does not include it for download size reasons.  

https://github.com/GovTechSG/purple-a11y/commit/abd9831fd616a018a932663d0a126b1d0bfb5a4d

**Pull request merged**
